name: Cakecommerce

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    env:
      working-directory: './web/app/cakecommerce'
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      working-directory: ${{env.working-directory}}
      run: composer validate

    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Composer lint
      working-directory: ${{env.working-directory}}
      run: composer lint
